package io.ucc.app.data.crypto

import java.security.GeneralSecurityException
import javax.crypto.Cipher
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/** Encodes bytes before they hit disk and decodes them on the way back. */
interface FileCodec {
    fun encode(plain: ByteArray): ByteArray

    /** @throws CorruptOrForeign when the bytes are not something this codec wrote (or the key changed). */
    fun decode(stored: ByteArray): ByteArray

    class CorruptOrForeign(message: String, cause: Throwable? = null) : Exception(message, cause)
}

/** Identity codec: used by tests and nowhere in production. */
object PlainCodec : FileCodec {
    override fun encode(plain: ByteArray): ByteArray = plain
    override fun decode(stored: ByteArray): ByteArray = stored
}

/**
 * AES-256-GCM whole-file encryption.
 *
 * Layout: `"UCC1"` magic · 1 byte IV length · IV · ciphertext+tag. The IV is
 * generated by the cipher on every write (never reused), the magic is bound as
 * associated data so a file cannot be swapped between store types.
 *
 * The key comes from a provider so the same code runs against the Android
 * Keystore in production ([KeystoreKeys]) and against an in-memory key in tests.
 */
class AesGcmFileCodec(private val key: () -> SecretKey, private val magic: ByteArray = MAGIC) : FileCodec {

    override fun encode(plain: ByteArray): ByteArray {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, key()) // IV chosen by the provider (Keystore enforces randomised IVs)
        cipher.updateAAD(magic)
        val iv = cipher.iv
        val ct = cipher.doFinal(plain)
        return magic + byteArrayOf(iv.size.toByte()) + iv + ct
    }

    override fun decode(stored: ByteArray): ByteArray {
        if (stored.size < magic.size + 1 || !stored.copyOfRange(0, magic.size).contentEquals(magic)) {
            throw FileCodec.CorruptOrForeign("missing magic")
        }
        val ivLen = stored[magic.size].toInt() and 0xff
        val ivStart = magic.size + 1
        if (ivLen !in 12..16 || stored.size < ivStart + ivLen + TAG_BYTES) throw FileCodec.CorruptOrForeign("bad header")
        val iv = stored.copyOfRange(ivStart, ivStart + ivLen)
        val ct = stored.copyOfRange(ivStart + ivLen, stored.size)
        return try {
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.DECRYPT_MODE, key(), GCMParameterSpec(TAG_BITS, iv))
            cipher.updateAAD(magic)
            cipher.doFinal(ct)
        } catch (e: GeneralSecurityException) {
            throw FileCodec.CorruptOrForeign(e.javaClass.simpleName, e)
        }
    }

    companion object {
        val MAGIC: ByteArray = "UCC1".toByteArray(Charsets.US_ASCII)
        private const val TRANSFORMATION = "AES/GCM/NoPadding"
        private const val TAG_BITS = 128
        private const val TAG_BYTES = TAG_BITS / 8

        fun isEncrypted(bytes: ByteArray): Boolean = bytes.size >= MAGIC.size && bytes.copyOfRange(0, MAGIC.size).contentEquals(MAGIC)
    }
}
